from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from apps.common.models import BaseModel


class Notification(BaseModel):
    """A basic system reminder - generated by the daily
    send_due_reminders management command (see apps.notifications.services),
    not manually. Global, not per-user: is_read is a single shared flag,
    since this is a small shop with one or a few Admin/Staff users, not a
    per-recipient inbox."""

    class Type(models.TextChoices):
        DUE_INVOICE = "DUE_INVOICE", "Due Invoice"
        LOAN_INSTALLMENT_DUE = "LOAN_INSTALLMENT_DUE", "Loan Installment Due"

    type = models.CharField(max_length=30, choices=Type.choices)
    title = models.CharField(max_length=200)
    message = models.TextField()
    due_date = models.DateField(null=True, blank=True)
    is_read = models.BooleanField(default=False)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.CharField(max_length=64, null=True, blank=True)
    related_object = GenericForeignKey("content_type", "object_id")

    class Meta:
        ordering = ["-created_at"]
        indexes = [models.Index(fields=["content_type", "object_id"])]

    def __str__(self):
        return f"{self.get_type_display()}: {self.title}"
