# Generated by Django 6.0.7 on 2026-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_seed_mileage_correction_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
