# Generated by Django 6.0.7 on 2026-07-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallmentpayment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='loan-installment-payments/'),
        ),
    ]
