# Generated by Django 6.0.7 on 2026-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='had_shortfall',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
