# Generated by Django 6.0.7 on 2026-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_had_shortfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_note',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
