# Generated by Django 6.0.7 on 2026-07-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('invoices', '0003_invoice_discount_amount_invoice_discount_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceserviceline',
            name='asset_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_service_lines', to='assets.asset'),
        ),
    ]
