# Generated by Django 6.0.7 on 2026-07-22 19:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_description'),
        ('invoices', '0004_invoiceserviceline_asset_used'),
        ('products', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='waived_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='waived_note',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='invoiceproductline',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoiceserviceline',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoiceserviceline',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceserviceline',
            name='product_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_service_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoicemeterentry',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceserviceline',
            name='asset_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_service_lines_as_tool', to='assets.asset'),
        ),
    ]
